### ISSUE TITLE
Requirment for bootstrap

### ISSUE THREAD

**Issue by Serhioromano** [benmarch/angular-bootstrap-tour#1]
The angular UI bootstrap works without bootstrap.js and jQuery.js

How possible it is to use this wrapper without bootstrap.js and jQuery.js? Can we use only CSS to style popups and angular to show them? Just like dropdowns in angular-ui-bootstrap?

**Comment by benmarch** [comment]
I haven't forgotten about this issue, I'm just trying to determine a good approach to solving the problem :)

**Comment by Serhioromano** [comment]
I am also not forgotten it and still waiting for a solution.

**Comment by benmarch** [comment]
Ok, I think I'm going to create a new plugin that is built specifically for Angular UI Bootstrap instead of the original jQuery-based Bootstrap. I'll keep the interface the same, but it won't require bootstrap.js or jquery; however, it will require angular-ui-bootstrap.js because I'm not going to redo some the fantastic work that they have done. I'm not sure what the timeframe will be, but I'll try to get it done in the next 6-8 weeks or so.

**Comment by Serhioromano** [comment]
> however, it will require angular-ui-bootstrap.js

That is ok. Anyone who use twitter bootstrap with angular use angular-ui-bootstrap anyway.

**Comment by no-more** [comment]
Hello,

Great job, is the jquery free release already available ?

**Comment by benmarch** [comment]
Unfortunately it is not; I have been slammed with other projects for months and it doesn't look like I will be able to really get it going until after July 7th.

**Comment by cklemming** [comment]
+1 for requesting the JQuery-free version.

**Comment by wald-tq** [comment]
are there any news?

**Comment by benmarch** [comment]
Yes, I have tried a couple different approaches including rewriting Bootstrap Tour entirely, but because they keep coming out with new features I decided it wasn't work trying to keep up. So ultimately, I have to find a way to do this while still using the existing Bootstrap Tour. The only way that I can think of is to replace jQuery with a stub that only implements the features that they use. I have started working on this recently, and it turns out not to be as difficult or awkward as I thought it would be, there have only been a few speed bumps so far. Bootstrap Tour only uses a handful of features from jQuery, so I am partially cherry picking from the jQuery repo, and partially implementing the features myself (to make them much smaller.) The reason this is taking so long is because I have other projects that take priority, and since my employer doesn't need this to be jQuery-free, I can only work on this in my free time. Thank you for inquiring though, I hope to roll this out by the end of the year.

**Comment by wald-tq** [comment]
Thanks for the response.

My app is a angular app. And we are looking to integrate a kind of a tour / onboarding experience. I think a valid option would be to just have the tour part separately from the core application.

So we could also use vanilla bootstrap tour (One teammember has already experience with it).

Do you see any downside to this other than loading time / size?

**Comment by benmarch** [comment]
The loading time is definitely a downside, especially if you aren't using jQuery in your core app. But if you can bundle up all the code into one dependency then at least it will be easy to swap out when there is a better option available (hopefully this plugin). I think that's probably a decent interim solution.

**Comment by benmarch** [comment]
Hey everyone, I am very excited to show you the jQuery-free version of the tour! Check it out: https://github.com/benmarch/angular-ui-tour

It is a work in progress, and the only release is a dev release so that I can get some feedback from all of you. I intentionally created a new repo so that I can continue to support the jQuery version.

Thank you all for your patience and supporting this plugin!
