### ISSUE TITLE
I want to change the prev and next to icons how can i change them to icons??

### ISSUE THREAD

**Issue by priyankabachu** [benmarch/angular-bootstrap-tour#44]

**Comment by benmarch** [comment]
Hey @priyankabachu, 

In order to change the popover template, you can create a partial and use the template-url option to point to it. Start by copying the template from the [Bootstrap Tour source code](https://github.com/sorich87/bootstrap-tour/blob/master/src/coffee/bootstrap-tour.coffee#L27-L42) and paste it into an HTML file or a text/ng-template script tag. Then on the tour element you can specify a template-url attribute that points to your partial (see the readme for example.) Please update your version of angular-bootstrap-tour to 0.3.4-rc.2 and let me know if this works for you.

Thanks,
Ben

**Comment by priyankabachu** [comment]
HI @benmarch It worked thank you so much !!!! :) :+1:

**Comment by benmarch** [comment]
Awesome! I will release that as 0.3.4.
