### ISSUE TITLE
How to give url to maintain the flow of the tour

### ISSUE THREAD

**Issue by suriyagp** [benmarch/angular-bootstrap-tour#5]
can give the path="url-to-go" as attribute inside the tag? where we are specifiying the tour order.

Is possible to specify the path like the above???

**Comment by benmarch** [comment]
I have added this functionality to 0.3.0.

To use it you will specify either a nextPath or prevPath (or both) and a nextStep or prevStep. For example:

``` HTML view1.html
<div tour-step="step1" title="Step 1 on View 1" next-path="view2" next-step="step2">...</div>

<div tour-step="step3" title="Step 3 on View 1" prev-path="view2" prev-step="step2">...</div>
```

``` HTML view2.html
<div tour-step="step2" title="Step 2 on View 2" next-path="view1" next-step="step3" prev-path="view1" prev-step="step1">...</div>
```

When you start the tour on page 1, the tour will load up step 1 first. When you click next it will navigate to '/view2' and load up step 2. When you click next on step 2 it will navigate back to view1 and load up step 3. Notice step 2 has a next and prev option so that it will be continuous regardless of the direction you are touring in.

This does not allow for navigation other than Angular routing ATM, but I can build into the next release. Hopefully this will cover your case for now.

The reason we can't use "path" the way that BT uses it is because in BT all the steps are laid out up front and it can determine how to navigate through them. But because we use directives to create the list of steps there is no way for us to know if there is another step on a different page. Using prev and next will create a simple flow control mechanism that can be expanded to same page navigation using step names instead of numeric orders, and multiple page navigation using browser navigation instead of Angular routing.

Take a look at the updated demo to see it in action.
