### ISSUE TITLE
Element - Step Options not working

### ISSUE THREAD

**Issue by Bezmundo** [benmarch/angular-bootstrap-tour#9]
I'm trying to get the the div containing the tour directive to get the popover to show over another html element. 
It just seems to ignore the element setting.

<code>
"tour-step element="#element" order="1" title="Tour start" content="Welcome to the tour" placement="bottom"
</code>

Is there anyway for the popover to display over another element?

**Comment by benmarch** [comment]
The way it is set up, the popover will display on the element that has the tourStep directive on it. Is there a reason the tourStep cannot be on `#element`?

**Comment by Bezmundo** [comment]
The reason it can't be on the element direct is because the tour is in a separate Partial view from the navigation. (Its a c# mcv app you see)

**Comment by benmarch** [comment]
We have a similar architecture where we are using it, but we were able to put the tourSteps in each of the partials that needed them. I understand that this is a separation of concerns issue, but we were comfortable breaking the practice in this case. Unfortunately, this plugin will not accept a different element to display the popover on, and since I am working on rewriting it without jQuery I don't think I will implement this feature here. My apologies.

**Comment by Bezmundo** [comment]
Thats fair enough, do other methods such as addStep been implemented?

**Comment by benmarch** [comment]
You can hack at by calling addStep() on the controller, but this plugin was designed to be declarative. Once you start using an imperative paradigm, it might make sense to use [Bootstrap Tour](http://www.bootstraptour.com).
